language: erlang

env:
  - LUA="th"

branches:
  only:
    - master

install:
  - echo "==== Installing dependencies ===="
  - sudo curl -sk https://raw.github.com/torch/ezinstall/master/install-deps | bash > /dev/null
  - echo "==== Installing Torch ===="
  - sudo curl -sk https://raw.github.com/torch/ezinstall/master/install-luajit+torch | bash > /dev/null
  - echo "==== Building torch-dokx ===="
  - sudo luarocks make
  - sudo dokx-luarocks make

script: "for x in tests/test*.lua ; do th $x ; done"

notifications:
  recipients:
    - danhgn@gmail.com
  email:
    on_success: change
    on_failure: always
