language: erlang

env:
  - LUA="th"

branches:
  only:
    - master

install:
  - echo "==== Installing virtualenv ===="
  - sudo pip install virtualenv
  - echo "==== Installing dependencies ===="
  - curl -sk https://raw.github.com/torch/ezinstall/master/install-deps | sudo bash &> /dev/null
  - echo "==== Installing Torch ===="
  - curl -sk https://raw.github.com/torch/ezinstall/master/install-luajit+torch | sudo bash &> /dev/null
  - echo "==== Building torch-dokx, using luarocks ===="
  - sudo luarocks make &> /dev/null
  - echo "==== Building torch-dokx with documentation, using doxk-luarocks ===="
  - sudo dokx-luarocks make &> /dev/null

script: 'for x in tests/test*.lua ; do echo "==== $x ====" ; th $x ; done'

notifications:
  recipients:
    - danhgn@gmail.com
  email:
    on_success: change
    on_failure: always
